controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_lucky_number_init:
    path: /lucky/number/{max}
    controller: App\Controller\LuckyController::numberInit